[language-server.clangd]
command = "clangd-18"

[[language]]
name = "c"
auto-format = true
formatter = {command = "clang-format-18"}

[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true

[[language]]
name = "bash"
file-types = [{glob = "config"}, "sh"]

# # for armv7-unknown-linux-gnueabihf, need to disable in other
# [language-server.rust-analyzer.config.cargo]
# target = "armv7-unknown-linux-gnueabihf"
